apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-world-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hello-world-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
